#!/usr/bin/env bash
set -euo pipefail

# AppImage builder — runs in CI (ubuntu-latest) after cargo build --release.
# Creates an AppDir and packs it with appimagetool into dist/markdown-library-<version>.AppImage.

BINARY=target/release/markdown-library
OUT_DIR=dist
APPDIR="${OUT_DIR}/MarkdownEditor.AppDir"

if [ ! -x "${BINARY}" ]; then
  echo "Error: binary not found: ${BINARY}" >&2
  exit 1
fi

version="${1:-}"
if [ -z "${version}" ]; then
  # Try to read version from Cargo.toml
  version="$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/')"
fi

rm -rf "${APPDIR}"
mkdir -p "${APPDIR}/usr/bin" \
         "${APPDIR}/usr/share/applications" \
         "${APPDIR}/usr/share/icons/hicolor/256x256/apps"

cp "${BINARY}" "${APPDIR}/usr/bin/markdown-library"

# Desktop entry
cat > "${APPDIR}/markdown-library.desktop" <<EOF
[Desktop Entry]
Name=Markdown Library
Exec=markdown-library
Icon=markdown-library
Type=Application
Categories=Utility;TextEditor;
EOF
cp "${APPDIR}/markdown-library.desktop" "${APPDIR}/usr/share/applications/"

# Use the icon generated by build.rs if available; fall back to a transparent placeholder
icon_src="$(find target/release/build -name icon.png -print -quit 2>/dev/null || true)"
if [ -n "${icon_src}" ]; then
  cp "${icon_src}" "${APPDIR}/usr/share/icons/hicolor/256x256/apps/markdown-library.png"
else
  # 1x1 transparent PNG
  printf '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\x0bIDATx\x9cc\x00\x00\x00\x02\x00\x01\xe5\x27\xde\xfc\x00\x00\x00\x00IEND\xaeB`\x82' \
    > "${APPDIR}/usr/share/icons/hicolor/256x256/apps/markdown-library.png"
fi

# Download appimagetool
APPIMAGETOOL=/tmp/appimagetool.AppImage
if [ ! -x "${APPIMAGETOOL}" ]; then
  echo "Downloading appimagetool..."
  wget -q -O "${APPIMAGETOOL}" \
    "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
  chmod +x "${APPIMAGETOOL}"
fi

# appimagetool must run outside the project dir or it may pick up stray files
WORKDIR="$(mktemp -d)"
echo "Creating AppImage in ${WORKDIR}..."
ARCH=x86_64 "${APPIMAGETOOL}" "${APPDIR}" "${WORKDIR}/markdown-library-${version}-x86_64.AppImage"

# Move result to dist
mv "${WORKDIR}/markdown-library-${version}-x86_64.AppImage" "${OUT_DIR}/"
rm -rf "${WORKDIR}"

echo "AppImage ready: ${OUT_DIR}/markdown-library-${version}-x86_64.AppImage"
